spring:
  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect:
          storage_engine: ${JPA_STORAGE_ENGINE:innodb}
        format_sql: ${JPA_FORMAT_SQL:true}
        show_sql: ${JPA_SHOW_SQL:true}
        use_sql_comments: ${JPA_USE_SQL_COMMENTS:true}
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:info}
    org.hibernate.SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL:debug}
  file:
    name: ${LOGGING_FILE_NAME:}
    path: ${LOGGING_FILE_PATH:}

output:
  ansi:
    enabled: ${SPRING_OUTPUT_ANSI_ENABLED:always}
